// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAuthLine.Models;

#nullable disable

namespace OAuthLine.Migrations
{
    [DbContext(typeof(OAuthLineContext))]
    partial class OAuthLineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("OAuthLine.Models.LineIdentity", b =>
                {
                    b.Property<int>("LineIdentityKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginIdToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LineIdentityKey");

                    b.ToTable("LineIdentity", (string)null);
                });

            modelBuilder.Entity("OAuthLine.Models.LineNotifySendDt", b =>
                {
                    b.Property<int>("LineNotifySendDtKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineIdentityKey")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LineNotifySendMtId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isSuccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineNotifySendDtKey");

                    b.ToTable("LineNotifySendDt", (string)null);
                });

            modelBuilder.Entity("OAuthLine.Models.LineNotifySendMt", b =>
                {
                    b.Property<int>("LineNotifySendMtKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LineNotifySendMtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("TEXT");

                    b.HasKey("LineNotifySendMtKey");

                    b.ToTable("LineNotifySendMt", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
